name: video_manageer
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: {sdk: '>=2.17.1 <3.0.0'}
dependencies:
  flutter: {sdk: flutter}
  get: ^4.1.4
  bitsdojo_window: ^0.1.2
  cupertino_icons: ^1.0.2
  lottie: ^1.0.1
  crypto: ^3.0.1
  convert: ^3.0.0
  fluttertoast: ^8.0.7
  flutter_screenutil: ^5.0.0+2
  dio_cookie_manager: ^2.0.0
  flutter_svg: ^0.22.0
dev_dependencies:
  flutter_test: {sdk: flutter}
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets: [assets/image/bg.jpg]
