/// Generated by Flutter GetX Starter on 2022-06-25 17:03
import 'package:flutter/material.dart';
import 'package:get/get_navigation/get_navigation.dart';

import 'app/routes/app_pages.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      initialRoute: Routes.VIDEO_MANAGER,
      getPages: AppPages.pages,
    );
  }
}