/// Generated by Flutter GetX Starter on 2022-06-27 17:48
import 'package:dart_vlc/dart_vlc.dart';
import 'package:flutter/material.dart';
import 'package:get/get_navigation/get_navigation.dart';

import 'app/routes/app_pages.dart';


Future<void> main() async {
  await DartVLC.initialize(useFlutterNativeView: true);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      initialRoute: Routes.VIDEO_MANAGER,
      getPages: AppPages.pages,
    );
  }
}